[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
